apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: ecommerce
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      imagePullSecrets:
      - name: dockerhub-secret
      containers:
      - name: backend
        image: khaledhawil/my-app:itiBack-1.0.3-build.16
        ports:
        - containerPort: 5000
        env:
        - name: MONGODB_URI
          valueFrom:
            configMapKeyRef:
              name: ecommerce-config
              key: MONGODB_URI
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: ecommerce-config
              key: PORT
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: ecommerce-config
              key: NODE_ENV
        - name: JWT_SECRET
          valueFrom:
            configMapKeyRef:
              name: ecommerce-config
              key: JWT_SECRET
        - name: PAYPAL_CLIENT_ID
          valueFrom:
            configMapKeyRef:
              name: ecommerce-config
              key: PAYPAL_CLIENT_ID
        - name: AWS_REGION
          valueFrom:
            configMapKeyRef:
              name: ecommerce-config
              key: AWS_REGION
        - name: AWS_BUCKET_NAME
          valueFrom:
            configMapKeyRef:
              name: ecommerce-config
              key: AWS_BUCKET_NAME
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: ecommerce-secrets
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: ecommerce-secrets
              key: AWS_SECRET_ACCESS_KEY
        resources:
          limits:
            memory: "256Mi"
            cpu: "200m"
          requests:
            memory: "128Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /api/products
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/products
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: ecommerce
spec:
  selector:
    app: backend
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  type: ClusterIP
