apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: ecommerce
data:
  NODE_ENV: production
  PORT: "5000"
  MONGODB_URI: mongodb://admin:password@mongodb-service:27017/amazona?authSource=admin
