apiVersion: v1
kind: ConfigMap
metadata:
  name: ecommerce-config
  namespace: ecommerce
data:
  MONGODB_URI: "mongodb://admin:password@mongodb-service:27017/amazona?authSource=admin"
  PORT: "5000"
  NODE_ENV: "production"
  REACT_APP_API_URL: "http://backend-service:5000"  # Internal service URL for development
  JWT_SECRET: "somethingsecret"
  PAYPAL_CLIENT_ID: "sb"
  AWS_REGION: "us-east-1"
  AWS_BUCKET_NAME: "amazona20"
---
apiVersion: v1
kind: Secret
metadata:
  name: ecommerce-secrets
  namespace: ecommerce
type: Opaque
data:
  # Base64 encoded values - replace with your actual encoded AWS credentials
  # To encode: echo -n 'your-access-key' | base64
  AWS_ACCESS_KEY_ID: "QUtJQVNVU0pFREhNRU9VRlhLWDU="  # your-aws-access-key-id (base64)
  AWS_SECRET_ACCESS_KEY: "NXlmMy9hMXhiK2x2SHREQ0lzb2doblR0QjdydVc2eGJpUWlKYnBUdQ=="  # your-aws-secret-access-key (base64)
  MONGO_INITDB_ROOT_USERNAME: "YWRtaW4="  # admin (base64)
  MONGO_INITDB_ROOT_PASSWORD: "cGFzc3dvcmQ="  # password (base64)
# Note: dockerhub-secret is now managed separately via the create-dockerhub-secret.sh script
