apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: ecommerce
type: Opaque
data:
  # admin (base64 encoded)
  mongodb-username: YWRtaW4=
  # password (base64 encoded) 
  mongodb-password: cGFzc3dvcmQ=
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: ecommerce
type: Opaque
data:
  # your-jwt-secret (base64 encoded)
  jwt-secret: eW91ci1qd3Qtc2VjcmV0
