
# ---
# - name: Cloud_Watch_Agent_Logs_Play
#   hosts: all
#   gather_facts: false
#   roles:
#     - Cloud_Watch_Agent_Installation



# -  name: Install Jenkins on EC2
#    hosts: jenkins_server
#    become: true 
#    roles:
#    - Jenkins_Server_Installation



# - name: Docker_installation_Play
#   hosts: jenkins_server
#   become: true
#   gather_facts: false
#   roles:
#  - Docker_installation

# - name: Argocd_Installation_Play
#   hosts: localhost
#   connection: local
#   gather_facts: false
#   become: false
#   tasks:  
#     - name: Argocd_Installation
#       command: bash Argocd_Installation.sh

- name: Install Trivy via Ansible Role
  hosts: jenkins_server
  become: true
  roles:
    - trivy_installation
